language: c

compiler: gcc

sudo: require

service:
  - docker

git:
  depth: false

## NOTIFICATIONS
notifications:
  email:
    recipients:
    - julien.tauran@epitech.eu
    on_success: always
    on_failure: always

jobs:
    include :
        - stage: build
          name: "Build"
          install:
            - docker pull epitechcontent/epitest-docker
          script:
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app && make fclean && make"

////////////////////////////////////////////

env:
  global:
    - CODECOV_TOKEN=:0caea449-ef00-44df-89a4-87bd613f3bc7

# after_success:
#   - bash <(curl -s https://codecov.io/bash)
